### ISSUE TITLE
Crash on startup collective-1.19.3-6.30

### ISSUE THREAD

**Issue by lospejos** [ricksouth/serilum-mc-mod-sources#2]
Minecraft with mod `collective-1.19.3-6.30` crashing on startup.
I have plenty mods depending on `collective`.

Crash log:
```
[16:22:14] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12
[16:22:14] [ForkJoinPool-1-worker-13/WARN]: The mod "wabi_sabi_structures" contains invalid entries in its mod json:
- Unsupported root entry "pack_format" at line 24 column 18
[16:22:14] [main/WARN]: Mod resolution failed
[16:22:14] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE doubledoors-fabric 3.9 {depends collective-fabric @ [>=5.23]}, ROOT_FORCELOAD_SINGLE doubledoors-fabric 3.9]
[16:22:14] [main/INFO]: Reason: [HARD_DEP doubledoors-fabric 3.9 {depends collective-fabric @ [>=5.23]}, HARD_DEP giantspawn-fabric 3.4 {depends collective-fabric @ [>=5.23]}, HARD_DEP netherportalspread-fabric 6.6 {depends collective-fabric @ [>=5.23]}, HARD_DEP randommobeffects-fabric 2.5 {depends collective-fabric @ [>=5.23]}, HARD_DEP villagespawnpoint-fabric 3.1 {depends collective-fabric @ [>=5.23]}]
[16:22:14] [main/INFO]: CLIENT environment disabled: [polymer-autohost]
[16:22:14] [main/INFO]: Fix: add [add:collective-fabric 5.23 ([[5.23,∞)])], remove [], replace []
[16:22:14] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install collective-fabric, version 5.23 or later.
Unmet dependency listing:
	 - Mod 'Double Doors (Fabric)' (doubledoors-fabric) 3.9 requires version 5.23 or later of collective-fabric, which is missing!
	 - Mod 'Giant Spawn (Fabric)' (giantspawn-fabric) 3.4 requires version 5.23 or later of collective-fabric, which is missing!
	 - Mod 'Nether Portal Spread (Fabric)' (netherportalspread-fabric) 6.6 requires version 5.23 or later of collective-fabric, which is missing!
	 - Mod 'Random Mob Effects (Fabric)' (randommobeffects-fabric) 2.5 requires version 5.23 or later of collective-fabric, which is missing!
	 - Mod 'Village Spawn Point (Fabric)' (villagespawnpoint-fabric) 3.1 requires version 5.23 or later of collective-fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[?:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) ~[?:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) ~[?:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[?:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[?:?]
```

Please note when I use `collective-1.19.3-6.21` (which BTW has file size twice more as `collective-1.19.3-6.30`) not changing other mods/settings  everything works fine.

Please assist.

Thanks.

**Comment by ricksouth** [comment]
- Mod 'Double Doors 
	 - Mod 'Giant Spawn
	 - Mod 'Nether Portal Spread
	 - Mod 'Random Mob Effects
	 - Mod 'Village Spawn Point

You'll need to install the new mod versions of these mods. They're on a separate page, where the new versions and updates will remain. Sorry for the inconvenience, but it's definitely more future proof.

So instead of download Double Doors (Fabric) you'll need Double Doors. The CurseForge app can find them automatically, but otherwise the URL is https://curseforge.com/minecraft/mc-mods/double-doors, instead of the -fabric URL

**Comment by ricksouth** [comment]
The reason 6.23 works, is because after that I removed the temporary jar-in-jar'd Collective-Fabric file from it. Which is also why the next version is a lot lower in filezile.

**Comment by lospejos** [comment]
> * Mod 'Double Doors
>       
>       * Mod 'Giant Spawn
>       * Mod 'Nether Portal Spread
>       * Mod 'Random Mob Effects
>       * Mod 'Village Spawn Point
> 
> 
> You'll need to install the new mod versions of these mods. They're on a separate page, where the new versions and updates will remain. Sorry for the inconvenience, but it's definitely more future proof.
> 
> So instead of download Double Doors (Fabric) you'll need Double Doors. The CurseForge app can find them automatically, but otherwise the URL is https://curseforge.com/minecraft/mc-mods/double-doors, instead of the -fabric URL

Thanks for your reply!

**Comment by lospejos** [comment]
After updating mods everything working fine. I close this issue. Thanks!

**Comment by ricksouth** [comment]
Thanks for giving the mods a try! Glad it works.
